# Generated by Django 5.0.7 on 2024-08-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_collection_work_collection_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='work',
        ),
    ]
