# Generated by Django 5.0.7 on 2024-08-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workavailability',
            name='agencies_only',
        ),
        migrations.AddField(
            model_name='profile',
            name='agencies_only',
            field=models.BooleanField(default=False),
        ),
    ]
