# Generated by Django 5.0.7 on 2024-08-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_workavailability_agencies_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workavailability',
            name='minimum_fixed_price_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='workavailability',
            name='minimum_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
