# Generated by Django 5.0.7 on 2024-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_workavailability_minimum_fixed_price_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='present',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
