# Generated by Django 5.0.7 on 2024-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_education_degree_alter_education_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
