# Generated by Django 5.0.7 on 2024-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Gallery_Images/'),
        ),
        migrations.AlterField(
            model_name='workmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Work_Images/'),
        ),
        migrations.AlterField(
            model_name='workmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Work_Videos/'),
        ),
    ]
