# Generated by Django 5.0.7 on 2024-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_gallery_image_alter_workmedia_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='timeline',
            field=models.CharField(choices=[('ASAP', 'ASAP'), ('Within the next month', 'Within the next month'), ('Not urgent', 'Not urgent')], default='', max_length=50),
        ),
    ]
