# Generated by Django 5.0.7 on 2024-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_report_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
