# Generated by Django 5.0.7 on 2024-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_work_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
