# Generated by Django 5.0.7 on 2024-08-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_job_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='block',
            name='created_at',
        ),
    ]
